Net/CursorBlinkTime 1000
Net/CursorBlink 1
Gdk/UnscaledDPI 98304
Gdk/WindowScalingFactor 1
Gtk/EnableAnimations 1
Gtk/DecorationLayout "close,minimize,maximize:"
Net/ThemeName "pearOS"
Gtk/PrimaryButtonWarpsSlider 1
Gtk/ToolbarStyle 3
Gtk/MenuImages 1
Gtk/ButtonImages 1
Gtk/CursorThemeSize 24
Gtk/CursorThemeName "pearOS-dark"
Net/SoundThemeName "ocean"
Net/IconThemeName "pearOS"
Gtk/FontName "Noto Sans,  10"

