Net/CursorBlinkTime 1000
Net/CursorBlink 1
Gdk/UnscaledDPI 98304
Gdk/WindowScalingFactor 1
Gtk/EnableAnimations 1
Gtk/DecorationLayout "close,minimize,maximize:"
Net/ThemeName "pearOS-Dark"
Gtk/PrimaryButtonWarpsSlider 1
Gtk/ToolbarStyle 3
Gtk/MenuImages 1
Gtk/ButtonImages 1
Gtk/CursorThemeSize 24
Gtk/CursorThemeName "pearOS-cursors"
Net/SoundThemeName "ocean"
Net/IconThemeName "pearOS-light"
Gtk/FontName "Sen,  10"

