[Behavior]
AutoSelectionDelay=600
BookmarkOpenMethod=current_tab
ConfirmDelete=true
ConfirmTrash=false
DirInfoWrite=true
NoUsbTrash=false
QuickExec=true
SingleClick=false
SpatialMode=false

[Desktop]
BgColor=#b41b1d
FgColor=#ffffff
ShadowColor=#000000
ShowHidden=false
SortColumn=name
SortOrder=ascending
Wallpaper=/usr/share/extras/wallpapers/Default/dark-mode.jpg
WallpaperMode=stretch

[Dock]
BottomBreathingRoom=4
BottomGap=13
HorizontalPad=14
Launchers=applications:pearos-calendar.desktop, applications:pearos-todo.desktop, applications:pearos-contacts.desktop, applications:pearos-notes.desktop, applications:org.kde.elisa.desktop, applications:pearos-appstore.desktop, applications:org.kde.kdeconnect.app.desktop, applications:org.kde.gwenview.desktop, applications:org.kde.kmail2.desktop, applications:pearos-systemsettings.desktop
PinnedFiles=
VerticalPad=11

[FolderView]
BackupAsHidden=false
BigIconSize=64
GridSpacingBottom=5
GridSpacingLeft=0
GridSpacingRight=60
GridSpacingTop=0
IconViewTextAnchor=center
IconViewTextMarginBottom=0
IconViewTextMarginTop=0
IconViewTextSize=0
IconViewTextWeight=0
Mode=icon
ShadowHidden=false
ShowFilter=true
ShowFullNames=false
ShowHidden=false
ShowItemCount=0
SidePaneCategoryFontSize=12
SidePaneCategoryLeftPadding=10
SidePaneCategorySpacing=15
SidePaneCategorySpacingBottom=1
SidePaneFontWeight=60
SidePaneIconSize=20
SidePaneIconTextSpacing=7
SidePaneItemFontSize=12
SidePaneItemHorizontalPadding=8
SidePaneItemSpacing=0
SidePaneScrollBarMode=0
SidePaneSelectorColor=#606060
SidePaneSelectorOpacity=150
SidePaneSelectorRightInset=33
SmallIconSize=16
SortColumn=name
SortFolderFirst=true
SortOrder=ascending
ThumbnailIconSize=128
UseStacks=false

[System]
Archiver=file-roller
FallbackIconThemeName=elementary
OemplateTypeOnce=false
OnlyUserTemplates=false
SIUnit=false
SuCommand=gksu %s
TemplateRunApp=false
Terminal=konsole

[Thumbnail]
MaxThumbnailFileSize=4096
ShowThumbnails=true
ThumbnailLocalFilesOnly=true

[TopBar]
AutoHide=Never
Items=xyz.pearos.pearmenu, com.github.antroids.application-title-bar, PearAppTitle, org.kde.plasma.appmenu, PearPrivacy, org.kde.plasma.panelspacer, org.kde.plasma.systemtray, luisbocanegra.panelspacer.extended, PearWifi, PearBattery, org.kde.milou, PearControlCentre, PearClock, org.kde.plasma.panelspacer

[Volume]
AutoRun=true
CloseOnUnmount=true
MountOnStartup=true
MountRemovable=true

[Window]
AlwaysShowTabs=false
BackForwardGroupHeight=40
BackForwardGroupLeftOffset=0
BackForwardGroupMarginLeft=-10
BackForwardGroupMarginRight=7
BackForwardGroupWidth=77
BreadcrumbIconSize=16
ContentTopPadding=70
FixedHeight=480
FixedWidth=640
HiddenSidebarItems=
IconGroupingGroupHeight=40
IconGroupingGroupMarginLeft=15
IconGroupingGroupMarginRight=10
IconGroupingGroupWidth=15
LastWindowHeight=595
LastWindowMaximized=false
LastWindowWidth=865
MainWindowTint=8
RememberWindowSize=true
ScrollBarWidth=20
SearchBarExpandWidth=1110
SearchButtonGroupHeight=40
SearchButtonGroupMarginLeft=0
SearchButtonGroupMarginRight=-5
SearchButtonGroupWidth=0
ShareTagsMoreGroupHeight=0
ShareTagsMoreGroupMarginLeft=4
ShareTagsMoreGroupMarginRight=4
ShareTagsMoreGroupWidth=0
ShowTabClose=true
SidePaneMode=places
SidePaneTopOffset=-8
SidebarTint=7
SplitterPos=260
TintWindow=1
ToolbarIconInnerSize=20
ToolbarIconOuterSize=32
ToolbarIconPadding=6
Transparency=1
TransparencyPower=1
ViewModeCollapseWidth=900
ViewOptionsGroupHeight=40
ViewOptionsGroupMarginLeft=0
ViewOptionsGroupMarginRight=0
ViewOptionsGroupWidth=170
WindowTopBlurBrightness=110
WindowTopBlurHeight=70
WindowTopBlurKeyColor=#282729
WindowTopBlurKeyTolerance=40
WindowTopBlurOpacity=90
WindowTopBlurPower=50
WindowTopBlurSaturation=250
